debug: false

management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

astra:
  api:
    application-token: ${ASTRA_APPLICATION_TOKEN}
    database-id: 3ed03fe0-3917-4e14-9461-69db565c3589
    database-region: westeurope
    cross-region-failback: false
    grpc:
      enabled: true
  cql:
    enabled: true
    download-scb:
      # if disabled zip files must be in folder (path)
      enabled: true
      # Looking for files scb_dbid-dbregion.zip in folder (default is ~/.astra/scb)
      # path: /tmp
    driver-config:
      basic:
        session-keyspace: spring_cassandra
